-- Ciclos FOR LOOP

/*
USE O LOOP BÁSICO QUANDO AS INTRUÇÕES DENTRO DO LOOP
PRECISAREM SER EXECUTADAS PELO MENOS UMA VEZ.

USE O LOOP WHILE SE A CONDIÇÃO PRECISAR SER AVALIADA NO INÍCIO
DE CADA ITERAÇÃO;

USE UM LOOP FOR SER O NÚMERO DE ITERAÇÕES FOR CONHECIDO
*/

DECLARE
	V_COUNTRYID   LOCATIONS.COUNTRY_ID%TYPE := 'CA';
	V_LOC_ID	  LOCATIONS.LOCATION_ID%TYPE;
	V_COUNTER	  NUMBER(2) := 1;
	V_NEW_CITY	  LOCATIONS.CITY%TYPE :='Montreal';

BEGIN
	SELECT MAX(LOCATION_ID) INTO V_LOC_ID FROM LOCATIONS
		WHERE COUNTRY_ID = V_COUNTRYID;

	LOOP
		INSERT INTO LOCATIONS(LOCATION_ID, CITY, COUNTRY_ID) VALUES ((V_LOC_ID + V_COUNTER), V_NEW_CITY, V_COUNTRYID);
		V_COUNTER := V_COUNTER + 1;
		EXIT WHEN V_COUNTER > 3;
	END LOOP;

END;



DECLARE
	I NUMBER := 1;
BEGIN
	DELETE T1;
	LOOP
		INSERT INTO T1 VALUES(I, I);
		I := I+1;
		EXIT WHEN I>100;
	END LOOP;
END;








