-- TYPE E ROW TYPE

-- ROWTYPE é útil para colocar as informações em uma única variável


CREATE TABLE REGIAO(ID INTEGER, NOME_REG VARCHAR2(20));
CREATE TABLE MENSAGEM(msg Varchar2(100));


INSERT INTO REGIAO VALUES(1, 'Norte');
INSERT INTO REGIAO VALUES(2, 'Sul');
INSERT INTO REGIAO VALUES(3, 'Suldeste');
INSERT INTO REGIAO VALUES(4, 'Nordeste');
INSERT INTO REGIAO VALUES(5, 'Centro-Oeste');


-- COM %TYPE

DECLARE
	ID_REGIAO REGIAO.ID%TYPE;
	NOME_REGIAO REGIAO.NOME_REG%TYPE;
BEGIN
	--Delete mensagem; 
	ID_REGIAO := 5;
	SELECT NOME_REG INTO NOME_REGIAO FROM REGIAO WHERE ID=ID_REGIAO;
	INSERT
		INTO MENSAGEM VALUES ('A região código ' || TO_CHAR(ID_REGIAO) || ' é ' || NOME_REGIAO);
END;



-- COM %ROWTYPE


DECLARE
	R_REG REGIAO%ROWTYPE;
	V_ID INTEGER := 5;
BEGIN
	DELETE MENSAGEM;
	SELECT * INTO R_REG FROM REGIAO WHERE ID=V_ID;
	INSERT INTO MENSAGEM VALUES
		('A região código ' || TO_CHAR(R_REG.ID) || ' é ' || R_REG.NOME_REG );
	COMMIT;

END;
select * from mensagem;





-- MEU

CREATE TABLE EMPLOYEE(ID INTEGER, NAME VARCHAR2(50), LAST_NAME VARCHAR2(50), AGE NUMBER);
INSERT INTO EMPLOYEE VALUES(0001, 'ANTONIO', 'SILVA', 18);
INSERT INTO EMPLOYEE VALUES(0002, 'PEDRO', 'SILVA', 30);
INSERT INTO EMPLOYEE VALUES(0003, 'ALEX', 'ROSA', 47);

CREATE TABLE RELATORIO(NR NUMBER(8), TEXTO CHAR(100));


DECLARE 
    R_EMPLOYEE EMPLOYEE%ROWTYPE;
    V_EMPREGADO INTEGER := 0002;
    V_NAME_FULL VARCHAR(100);

BEGIN 

	SELECT * INTO R_EMPLOYEE FROM EMPLOYEE WHERE ID = V_EMPREGADO;
	v_NAME_FULL := TO_CHAR(R_EMPLOYEE.NAME || ' ' || R_EMPLOYEE.LAST_NAME);
	INSERT INTO RELATORIO VALUES(V_EMPREGADO, V_NAME_FULL);
	COMMIT;

END;


SELECT * FROM RELATORIO;